/:
  controller: main
  action: home 

/template:
  controller: main
  action: template

/login:
  controller: user
  action: login

/login-fb:
  controller: user
  action: loginwithfb

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/forget:
  controller: passwordrecovery
  action: pwdforget

/confirmation:
  controller: confirmation
  action: confirmation  

/reset-new-password:
  controller: confirmation
  action: confirmationPwd

/dashboard:
  controller: admin
  action: dashboard
  security:
    - admin
    - user

/dashboard/subscribe:
  controller: admin
  action: dashboard
  security:
    - admin
    - user

/dashboard/settings:
  controller: admin
  action: dashboard
  security:
    - admin
    - user

/payment:
  controller: payment
  action: payment

